import { type PlatformAdapter, resolve } from "./types";

interface TypeEntry {
  /** Module, on modular builds. */
  m?: string;
  /** Package. */
  p?: string;
  /** Type name, nested types dotted. */
  l?: string;
  /** Explicit URL, when the type lives elsewhere. */
  u?: string;
}

/** Javadoc: the type search index lists every class page. */
export const javadoc: PlatformAdapter = {
  name: "javadoc",
  async detect(pageUrl, html, fetchText) {
    const pathToRoot = /var\s+pathtoroot\s*=\s*["']([^"']*)["']/i.exec(html)?.[1];
    const generated =
      /<meta[^>]+content=["']javadoc/i.test(html) || /Generated by javadoc/i.test(html);
    if (pathToRoot === undefined && !generated) return null;
    const root = resolve(pathToRoot || "./", pageUrl);
    const text = root ? await fetchText(`${root}type-search-index.js`) : undefined;
    if (!root || !text) return null;
    const json = text.slice(text.indexOf("["), text.lastIndexOf("]") + 1);
    try {
      const types = JSON.parse(json) as TypeEntry[];
      const pages = new Set<string>();
      for (const type of types) {
        if (!type.l || type.l === "All Classes and Interfaces") continue;
        const path =
          type.u ??
          `${type.m ? `${type.m}/` : ""}${(type.p ?? "").replace(/\./g, "/")}/${type.l}.html`;
        const url = resolve(path, root);
        if (url) pages.add(url);
      }
      return { witness: "javadoc index", pages: [...pages] };
    } catch {
      return null;
    }
  },
};
